/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Color = IDL.Record({
  'hex' : IDL.Text,
  'name' : IDL.Text,
  'family' : IDL.Text,
});
export const VoteStats = IDL.Record({ 'votes' : IDL.Nat, 'likes' : IDL.Nat });
export const Session = IDL.Record({
  'season' : IDL.Text,
  'familyStats' : IDL.Vec(IDL.Tuple(IDL.Text, VoteStats)),
  'colors' : IDL.Vec(IDL.Tuple(Color, IDL.Bool)),
});

export const idlService = IDL.Service({
  'addVote' : IDL.Func([IDL.Text, Color, IDL.Bool], [], []),
  'createSession' : IDL.Func([IDL.Text], [], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
  'getLikedColors' : IDL.Func([IDL.Text], [IDL.Vec(Color)], ['query']),
  'getRecommendedFamily' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getSession' : IDL.Func([IDL.Text], [Session], ['query']),
  'setSeason' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Color = IDL.Record({
    'hex' : IDL.Text,
    'name' : IDL.Text,
    'family' : IDL.Text,
  });
  const VoteStats = IDL.Record({ 'votes' : IDL.Nat, 'likes' : IDL.Nat });
  const Session = IDL.Record({
    'season' : IDL.Text,
    'familyStats' : IDL.Vec(IDL.Tuple(IDL.Text, VoteStats)),
    'colors' : IDL.Vec(IDL.Tuple(Color, IDL.Bool)),
  });
  
  return IDL.Service({
    'addVote' : IDL.Func([IDL.Text, Color, IDL.Bool], [], []),
    'createSession' : IDL.Func([IDL.Text], [], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(Session)], ['query']),
    'getLikedColors' : IDL.Func([IDL.Text], [IDL.Vec(Color)], ['query']),
    'getRecommendedFamily' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getSession' : IDL.Func([IDL.Text], [Session], ['query']),
    'setSeason' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };